### ISSUE TITLE
Browser Factory for Microsoft's Edge Browser

### ISSUE THREAD

**Issue by nt-ca-aqe** [testIT-WebTester/webtester2-core#28]
As with the `BrowserFactory` implementatins for Firefox, Chrome, Internet Explorer etc., we should provide an out of the box `EdgeFactory` for Microsoft's Edge browser.
- The `BrowserFactory` should be called `EdgeFactory`.
- Our default performance optimizations should be applied.

**Comment by slu-it** [comment]
implemented with #55
