### ISSUE TITLE
Default Properties documentation broken

### ISSUE THREAD

**Issue by Drakojin** [testIT-WebTester/webtester2-core#71]
Current Documentation shows:
https://oss.sonatype.org/service/local/repositories/snapshots/content/info/novatec/testit/webtester-documentation/2.9-SNAPSHOT/webtester-documentation-2.9-20190712.141410-1.html#_default_properties

Unresolved directive in chapters/configuration.asciidoc - include::/root/work/webtester-documentation/target/generated-snippets/config/default-configuration.snippet[]

**Comment by slu-it** [comment]
fixed with #74
